### ISSUE TITLE
Fix blind singing not working for some of the contract methods

### ISSUE THREAD

**Issue by rafal2228** [LedgerHQ/app-ethereum#311]
## Description

We're encountering an issue with the execution of some of the contract methods. Most notably we encounter it with a method named `mint` when working on our NFT collection. The problem seems to be dependent on the name of the method as renaming it to something else (f.e. `mintPublic`) solves the issue.

This seems to be already known issue as I was able to find related topics over the internet (but wasn't able to find an issue in this repo):
- https://www.reddit.com/r/ledgerwallet/comments/qyzky2/minting_fails_with_ledger_metamask_wallet_but/
- https://community.metamask.io/t/ledger-issue-please-enable-contract-data-but-its-already-enabled-and-enabling-debug-data-fixes-it/9679

**There is already known workaround** of turning on `Debug Data Displayed`, which solves the issue and allows transactions to be processed.

Also, it feels like the issue might be connected to the ledger Ethereum app, as switching the type of connection between MetaMask and Ledger from `WebHID` to `Ledger Live` doesn't make a difference.

Other similar issues that I found in this repo that might be connected:
- https://github.com/LedgerHQ/app-ethereum/issues/201
- https://github.com/LedgerHQ/app-ethereum/issues/230

## Your environment

* OS and version: Windows 10
* branch that causes this issue: N/A, used latests available version from Ledger Live store - `1.9.18`
* Device: Nano S

## Steps to reproduce

- Connect MetaMask and Ledger
- Try to execute a method named `mint` on Smart Contract - f.e. similar to [this one](https://etherscan.io/address/0x9A395013Afe7624E32B82e7F5035FAd3be77646C#code#F1#L1)

## Expected behavior

You should be able to interact with this method and mint NFT

## Actual behavior

MetaMask (and probably the ledger app) is returning an error saying:

`Please enable Blind signing or Contract data in the Ethereum app Settings`

## Logs

Error returned by MetaMask

```json
{"code":-32603,"message":"Please enable Blind signing or Contract data in the Ethereum app Settings"}
```

Error logged locally by contract
```sh
  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0)
      at async HardhatNode.runCall (/app/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:616:20)
      at async EthModule._callAction (/app/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:354:9)
      at async HardhatNetworkProvider._sendWithLogging (/app/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at async HardhatNetworkProvider.request (/app/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at async JsonRpcHandler._handleRequest (/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at async JsonRpcHandler._handleSingleRequest (/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at async Server.JsonRpcHandler.handleHttp (/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

Note. The same transaction works if we turn on `Debug Data Display`

## Proposed solution

Can't think of any

**Comment by tonisives** [comment]
I also have this issue with my NFT minting.
