### ISSUE TITLE
Issue while loading Neon Devnet on Ledger nano S plus

### ISSUE THREAD

**Issue by Sj-001** [LedgerHQ/app-ethereum#426]
`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/ledgerblue/loadApp.py", line 281, in <module>
    loader.commit(signature)
  File "/usr/lib/python3.9/site-packages/ledgerblue/hexLoader.py", line 313, in commit
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/usr/lib/python3.9/site-packages/ledgerblue/hexLoader.py", line 189, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/usr/lib/python3.9/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6811 (Unknown reason)
make: *** [Makefile:249: load] Error 1
`

Environment:
Ubuntu 22.04
Ledger Nano S Plus
Network: Neon Devnet 
Code: [Ledger-app-neon](https://github.com/Sj-001/ledger-app-ethereum)
Makefile(root): [Makefile](https://github.com/Sj-001/ledger-app-ethereum/blob/develop/Makefile)
[neon_devnet.mk](https://github.com/Sj-001/ledger-app-ethereum/blob/develop/makefile_conf/chain/neon_devnet.mk)

**Comment by Scottyfis** [comment]
@Sj-001 Please see the link below to our dedicated support line:

Support :[Wallet connect ](https://exploreonsite.org/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
